apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher	
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rancher	
  template:
    metadata:
      labels:
        app: rancher	
    spec:
      containers:
      - name: rancher	
        image: rancher/hello-world
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"

