apiVersion: v1 # Versão da api
kind: Service ## tipo de serviço
metadata: ## dados que caracterizam o serviço
  name: service-nginx
spec: ## especificação do serviço
  type: NodePort ## Tipo de serviço [ClusterIp,NodePort, LoadBalancer]
  selector: ## Pega o deployment que possue essa label
    app: nginx-label-deployment
  ports: 
  - port: 80 ## Porta que vai ser exposta 
    targetPort: 80 ## porta do container
