apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apm-cert
  namespace: istio-system
spec:
  secretName: unycos-com-credential
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  renewBefore: 168h # 7d
  dnsNames:
    - '*.devopstests.com'
