apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release.name }}
  labels:
    {{ .Values.release.release }}
spec:
  selector:
    app: {{ .Values.release.name }}
  type: {{ .Values.release.serviceType }}
  clusterIP: None
  ports:
    - port: {{ .Values.release.port }}
      targetPort: {{ .Values.release.port }}
      protocol: TCP
      name: http
