apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.release.name }}-vs
  namespace: istio-system
  labels:
    name: {{ .Values.release.name }}-vs
spec:
  hosts:
    - apm.devopstests.com
  gateways:
    - istio-system/apm-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ .Values.release.name }}.default.svc.cluster.local
