apiVersion: v1
kind: Service
metadata:
    name: apiservice
spec:
    type: NodePort
    selector:
        app: {{ .Values.nameDeployment}}
    ports:
    #Porta que vamos exportar para o mundo
    - port: 8080
    #Porta do serviço do deployment
      targetPort: 80